name: readian_workspace
description: "Multi-package workspace for Readian Flutter app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

workspace:
  - app/
  - packages/data
  - packages/domain
  - packages/presentation
  - packages/features