name: readian_features
description: "Feature modules for Readian app - contains all app features"
publish_to: 'none'
resolution: workspace

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Local packages
  readian_domain:
    path: ../domain
  readian_data:
    path: ../data
  readian_presentation:
    path: ../presentation
  readian_flutter:
    path: ../../app

  # State Management
  flutter_riverpod: ^2.6.0
  freezed_annotation: ^2.4.0

  # UI Components
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  flutter_lints: ^6.0.0